// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828162834_AddTapDedupIndex")]
    partial class AddTapDedupIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000201"),
                            Code = "201",
                            Name = "Аудиторія 201"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000303"),
                            Code = "303",
                            Name = "Аудиторія 303"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000105"),
                            Code = "105",
                            Name = "Лабораторія 105"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000402"),
                            Code = "402",
                            Name = "Аудиторія 402"
                        });
                });

            modelBuilder.Entity("Domain.Models.Tap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("RoomId", "UserId", "CreatedAt");

                    b.ToTable("Taps");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000001"),
                            FullName = "Іван Петренко",
                            GroupName = "КН-21"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000002"),
                            FullName = "Марія Коваленко",
                            GroupName = "КН-21"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000003"),
                            FullName = "Олег Шевчук",
                            GroupName = "ІПЗ-22"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000004"),
                            FullName = "Софія Бондаренко",
                            GroupName = "ІПЗ-22"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000005"),
                            FullName = "Андрій Мельник",
                            GroupName = "КБ-23"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000006"),
                            FullName = "Наталія Ткаченко",
                            GroupName = "КБ-23"
                        });
                });

            modelBuilder.Entity("Domain.Models.Tap", b =>
                {
                    b.HasOne("Domain.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
